
export const HEAD_OPTION_TYPE = {
  TYPE_SHOW_MESSAGE_LIST: 1,
  TYPE_SHOW_PHONE_LIST: 2,
  TYPE_SHOW_USER_INFO: 3,
  TYPE_SHOW_ADD_FRIEND_VIEW: 4,
  TYPE_SHOW_MORE_ZONE: 5,
  TYPE_SHOW_MORE_MENU: 6
}

export const MAIN_NAV_ID = {
  NAV_MESSAGE: 1,
  NAV_CONTACT: 2,
  NAV_ZONE: 3
}